<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.6"/>
    <xacro:property name="chassis_width" value="0.4"/>
    <xacro:property name="chassis_height" value="0.6"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.25"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0"/>

  <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
  </material>

   <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
   </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

   <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    
 <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>


  <!-- Wheels -->
  <joint name="front_left_wheel_joint" type="continuous">
    <origin xyz="0.275 0.225 0.03" rpy="-${pi/2} 0 0"/>
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="0.05" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="front_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="front_right_wheel_joint" type="continuous">
    <origin xyz="0.275 -0.225 0.03" rpy="${pi/2} 0 0"/>
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
       <xacro:inertial_cylinder mass="0.1" length="0.05" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="front_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="rear_left_wheel_joint" type="continuous">
    <origin xyz="-0.175 0.225 0.03" rpy="-${pi/2} 0 0"/>
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="rear_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="0.05" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="rear_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="rear_right_wheel_joint" type="continuous">
    <origin xyz="-0.175 -0.225 0.03" rpy="${pi/2} 0 0"/>
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="rear_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="0.05" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="rear_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Static Transformations -->
  <static_transform_publisher name="base_link_to_map" args="0 0 0 0 0 0 base_link map 100" />

</robot>